$ErrorActionPreference = 'Stop'
Set-Location 'C:\Users\vilen\OneDrive\Dokumentumok\PlatformIO\Projects\Smart_Platform'
$env:SMART_PLATFORM_RPI_HOST = '0.0.0.0'
$env:SMART_PLATFORM_RPI_PORT = '8091'
$env:SMART_PLATFORM_RPI_PUBLIC_BASE_URL = 'http://192.168.1.227:8091'
$env:SMART_PLATFORM_SYNC_ENABLED = '0'
& 'C:\Users\vilen\AppData\Local\Programs\Python\Python313\python.exe' 'C:\Users\vilen\OneDrive\Dokumentumok\PlatformIO\Projects\Smart_Platform\host_runtime\app.py' *>> 'C:\Users\vilen\OneDrive\Dokumentumok\PlatformIO\Projects\Smart_Platform\tools\runtime\rpi-shell-host.log'
